// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK28a-6zuJRWfsBBvKLqm-M4aZM6mvQPI',
    appId: '1:816534803753:web:21ef01c82c1e7887221338',
    messagingSenderId: '816534803753',
    projectId: 'rdp-todolist-57795',
    authDomain: 'rdp-todolist-57795.firebaseapp.com',
    storageBucket: 'rdp-todolist-57795.appspot.com',
    measurementId: 'G-XKGDEKWL4R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqLz6-zkMZBNjOPSDaapk4wFE6WRO_guo',
    appId: '1:816534803753:android:01cfcb7928c0c621221338',
    messagingSenderId: '816534803753',
    projectId: 'rdp-todolist-57795',
    storageBucket: 'rdp-todolist-57795.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7ld0PRxMk69EGM-EoSaVpX0lmioXfHjs',
    appId: '1:816534803753:ios:b83cde86c577b02c221338',
    messagingSenderId: '816534803753',
    projectId: 'rdp-todolist-57795',
    storageBucket: 'rdp-todolist-57795.appspot.com',
    iosBundleId: 'com.example.rdpTodolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7ld0PRxMk69EGM-EoSaVpX0lmioXfHjs',
    appId: '1:816534803753:ios:b83cde86c577b02c221338',
    messagingSenderId: '816534803753',
    projectId: 'rdp-todolist-57795',
    storageBucket: 'rdp-todolist-57795.appspot.com',
    iosBundleId: 'com.example.rdpTodolist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBK28a-6zuJRWfsBBvKLqm-M4aZM6mvQPI',
    appId: '1:816534803753:web:3c47239d997e7456221338',
    messagingSenderId: '816534803753',
    projectId: 'rdp-todolist-57795',
    authDomain: 'rdp-todolist-57795.firebaseapp.com',
    storageBucket: 'rdp-todolist-57795.appspot.com',
    measurementId: 'G-5EBDL4ETFS',
  );
}
